name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo apt install neofetch lshw
       
       - name: Neofetch
         run: |
              neofetch --stdout
       
       - name: lshw
         run: |
              lshw -short
       
       - name: Disk Space
         run: df -h
       
       - name: Drive info
         run: |
              lsblk             
